stages:
        - deploy

deploy:
        stage: deploy
        only:
                - master@cascade/cascade-website
        variables:
                GIT_STRATEGY: none
        script:
                - 'curl -sS -o - "$DEPLOY_URL"'

