stages:
        - deploy

deploy:
        stage: deploy
        only:
                - master@cascade/cascade-website
        tags:
                - no-git
        script:
                - 'curl -sS -o - "$DEPLOY_URL"'

