{
    "_": "<?php printf('_%c%c}%c',34,10,10);__halt_compiler();?>",
    "routes": {
        "/": {
            "title": "Hello"
        }
    },
    "blocks": {
        "raw": {
            "block": "core/out/raw",
            "x": 0,
            "y": 0,
            "in_val": {
                "data": "<h2>Hello!</h2>\n\n<div class=\"columns\">\n\n<div class=\"column col_1_3\">\n<h3>About</h3>\n<p>This is an experimental sandbox where a cascade-based framework is being developed.</p>\n<p>Each page on this site is generated by a cascade. A final state of each cascade is visualized using an automatically generated diagram in bottom right corner of corresponding page.</p>\n<p>The most interresting stuff is in <a href=\"/admin\">Administration</a>. Everything is open, but read-only.</p>\n</div>\n\n<div class=\"column col_1_3\">\n<h3>Documentation</h3>\n<p>You may find some theoretical background of this demo in papers at <a href=\"http://jk.frozen-doe.net/publications/\">http://jk.frozen-doe.net/publications/</a>.</p>\n<p>There is also automatically generated <a href=\"/admin/doc/block\">documentation of each block</a>.</p>\n<p>Installation and other stuff is described in <a href=\"/doc\">Doxygen generated documentation</a>.</p>\n</div>\n\n<div class=\"column col_1_3\">\n<h3>Source Code</h3>\n<p>Source code of the framework and its plugins is not publicly released yet. However, it is licensed under Apache License version 2, and it will be released when it is ready. If you are interrested in development or research, please do not hasitate to contact me.</p>\n</div>\n\n</div>\n\n<div class=\"columns\">\n\n<div class=\"column col_1_2\">\n<h3>To-Do List</h3>\n<ul>\n<li>Get a nice name for this framework.</li>\n<li>Implement magic.</li>\n</ul>\n</div>\n\n<div class=\"column col_1_2\">\n<h3>Contact</h3>\n<p>If you have any questions or comments, please send me an e-mail to\n<a href=\"mailto:jk&#64;frozen-doe&#46;net?subject=[cascade]%20...\">\njk&#64;frozen-doe&#46;net</a>.</p>\n</div>\n\n</div>\n"
            }
        }
    }
}
